language: python
cache: pip

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          python: 3.6

install:
    - pip install -r requirements.txt 

script:
    - python manage.py check
