# Generated by Django 2.0 on 2018-11-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    atomic = False
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dustbin_id', models.CharField(max_length=200)),
                ('percentage', models.IntegerField(verbose_name='percentage filled')),
                ('collect_time', models.DateTimeField(verbose_name='time collected')),
            ],
        ),
    ]
