# Generated by Django 2.1.3 on 2019-11-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('datavis', '0002_auto_20191119_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorePercentage',
            new_name='Dustbin',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='dustbin',
        ),
    ]
